@SecureWeatherApi_HostAddress = http://localhost:5168
@Access_JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VybmFtZSIsImp0aSI6IjFmYmQzMzcxLTdmZGItNGJkNS1iMjI3LTk3YWI3ZjkzYzJhOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ1c2VybmFtZSIsImV4cCI6MTczNDQ0NDAxNiwiaXNzIjoiU2VjdXJlQXBpV2l0aEpXVCIsImF1ZCI6IlNlY3VyZUFwaVVzZXJzIn0.YSoFFFqYDIm3OC8KzPTvAi88N3tenw6AXVodymYujng
@Refresh_Token = 9a40c791-5c50-4d1a-9b1e-d6b003efb2e9

GET {{SecureWeatherApi_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{Access_JWT}}
###

### Login Request
POST {{SecureWeatherApi_HostAddress}}/login/
Content-Type: application/json

{
    "username": "username",
    "password": "password"
}

### Refresh Token Request
POST {{SecureWeatherApi_HostAddress}}/refresh/
Content-Type: application/json

{
    "refreshToken": "{{Refresh_Token}}"
}