@SecureWeatherApi_HostAddress = http://localhost:5168
@Access_JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im90dG9yaW5vYnJ1bmkiLCJzdWIiOiJvdHRvcmlub2JydW5pIiwianRpIjoiZGVkYzgyOTciLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDoxMDM0MSIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzI0IiwiaHR0cDovL2xvY2FsaG9zdDo1MTY4IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzEzNyJdLCJuYmYiOjE3MzI4OTI3OTIsImV4cCI6MTc0MDc1NTE5MiwiaWF0IjoxNzMyODkyNzkzLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.dhEsj9fc8Bc86lVcBIPPX-mtFLbMwe16VY5G5F89ssE

GET {{SecureWeatherApi_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{Access_JWT}}
###
